version: 1.0.0.{build}.{branch}

nuget:
  account_feed: true
  
init:
 - git config --global core.autocrlf true
 
services:
  - mssql2014

cache:
  - HexaDotApp\Web-App\HexaDot\node_modules   #node modules for the app
  - '%APPDATA%\npm-cache'             # npm cache
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 - choco install firefox
 
before_build:
 - cmd: dotnet restore HexaDotApp
 - nuget restore HexaDotApp\HexaDot.IntegrationTest\HexaDot.ScenarioTest.fsproj -SolutionDirectory .\HexaDotApp
 - cmd: npm install gulp bower -g

build_script:
 - ps: (Get-Content HexaDotApp\Web-App\HexaDot\version.json).replace("GITVERSION", (git rev-parse --short HEAD)) | Set-Content HexaDotApp\Web-App\HexaDot\version.json
 - cmd: dotnet build HexaDotApp\HexaDot.Core\project.json
 - cmd: dotnet publish HexaDotApp\Web-App\HexaDot\project.json --output c:\Published
 - cmd: dotnet build HexaDotApp\Web-App\HexaDot.UnitTest\project.json
 - cmd: dotnet build HexaDotApp\HexaDot.NotificationsWebJob\project.json
 - cmd: msbuild HexaDotApp\HexaDot.IntegrationTest\HexaDot.ScenarioTest.fsproj

test_script:
 - ps: cd .\HexaDotApp\Web-App\HexaDot.UnitTest
 - cmd: dotnet test 


